### ISSUE TITLE
misleading project name

### ISSUE THREAD

**Issue by firepick1** [jaredlunde/flight-path#1]
The unfortunate choice of "flight-path" as a npm package name actually precludes the publication of an npm package "flight-path" pacakge that computes a ballistic trajectory. Not sure what  XMLHttpWrapper has to do with a flight path?

**Comment by jaredLunde** [comment]
It's a component to a React state manager / data fetcher I've written called Radar. The XMLHttpRequest is the planned course for the payload. It makes sense. Sorry to hear you have a conflict. Finding package names on npm is difficult. I should know, I spent an hour searching before I landed on this one. Good luck w/ your search.
